import { useEffect, useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogTrigger,
} from "../ui/dialog";
import { Button } from "../ui/button";
import { BrainCog, Loader } from "lucide-react";
import { ConfirmClearDialog } from "./ConfirmClearDialog";
import { TooltipIconButton } from "../ui/assistant-ui/tooltip-icon-button";
import { TighterText } from "../ui/header";
import { useStore } from "@/hooks/useStore";
import { useToast } from "@/hooks/use-toast";

export interface NoReflectionsProps {
  assistantId: string | undefined;
  getReflections: (assistantId: string) => Promise<void>;
}

function NoReflections(props: NoReflectionsProps) {
  const { assistantId } = props;
  const { toast } = useToast();

  const getReflections = async () => {
    if (!assistantId) {
      toast({
        title: "Error",
        description: "Assistant ID not found.",
        variant: "destructive",
        duration: 5000,
      });
      return;
    }
    await props.getReflections(assistantId);
  };

  return (
    <div className="flex flex-col items-center mt-6 mb-[-24px] gap-3">
      <TighterText>No reflections have been generated yet.</TighterText>
      <TighterText className="text-sm text-gray-500">
        Reflections generate after 30s of inactivity. If none appear, try again
        later.
      </TighterText>
      <Button onClick={getReflections} variant="secondary" size="sm">
        <TighterText>Search for reflections</TighterText>
      </Button>
    </div>
  );
}

interface ReflectionsDialogProps {
  assistantId: string | undefined;
}

export function ReflectionsDialog(props: ReflectionsDialogProps) {
  const { toast } = useToast();
  const [open, setOpen] = useState(false);
  const { assistantId } = props;
  const {
    isLoadingReflections,
    reflections,
    getReflections,
    deleteReflections,
  } = useStore();

  useEffect(() => {
    if (!assistantId || typeof window === "undefined") return;
    // Don't re-fetch reflections if they already exist & are for the same assistant
    if (
      (reflections?.content || reflections?.styleRules) &&
      reflections.assistantId === assistantId
    )
      return;

    getReflections(assistantId);
  }, [assistantId]);

  const handleDelete = async () => {
    if (!assistantId) {
      toast({
        title: "Error",
        description: "Assistant ID not found.",
        variant: "destructive",
        duration: 5000,
      });
      return false;
    }
    setOpen(false);
    return await deleteReflections(assistantId);
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <TooltipIconButton
          tooltip="Reflections"
          variant="ghost"
          className="w-fit h-fit p-2"
          onClick={() => setOpen(true)}
        >
          <BrainCog className="w-6 h-6 text-gray-600" />
        </TooltipIconButton>
      </DialogTrigger>
      <DialogContent className="max-w-xl p-8 bg-white rounded-lg shadow-xl">
        <DialogHeader>
          <DialogTitle className="text-3xl font-light text-gray-800">
            <TighterText>Reflections</TighterText>
          </DialogTitle>
          <DialogDescription className="mt-2 text-md font-light text-gray-600">
            <TighterText>
              {isLoadingReflections ? (
                "Loading reflections..."
              ) : reflections?.content || reflections?.styleRules ? (
                "Current reflections generated by the assistant for content generation."
              ) : (
                <NoReflections
                  assistantId={assistantId}
                  getReflections={getReflections}
                />
              )}
            </TighterText>
          </DialogDescription>
        </DialogHeader>
        <div className="mt-6 max-h-[60vh] overflow-y-auto pr-4 scrollbar-thin scrollbar-thumb-gray-300 scrollbar-track-gray-100">
          {isLoadingReflections ? (
            <div className="flex justify-center items-center h-32">
              <Loader className="h-8 w-8 animate-spin" />
            </div>
          ) : reflections?.content || reflections?.styleRules ? (
            <>
              {reflections?.styleRules && (
                <div className="mb-6">
                  <TighterText className="text-xl font-light text-gray-800 sticky top-0 bg-white py-2 mb-3">
                    Style Reflections:
                  </TighterText>
                  <ul className="list-disc list-inside space-y-2">
                    {reflections.styleRules?.map((rule, index) => (
                      <li key={index} className="flex items-baseline">
                        <span className="mr-2">•</span>
                        <TighterText className="text-gray-600 font-light">
                          {rule}
                        </TighterText>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              {reflections?.content && (
                <div className="mb-6">
                  <TighterText className="text-xl font-light text-gray-800 sticky top-0 bg-white py-2 mb-3">
                    Content Reflections:
                  </TighterText>
                  <ul className="list-disc list-inside space-y-2">
                    {reflections.content.map((rule, index) => (
                      <li key={index} className="flex items-baseline">
                        <span className="mr-2">•</span>
                        <TighterText className="text-gray-600 font-light">
                          {rule}
                        </TighterText>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </>
          ) : null}
        </div>
        <div className="mt-6 flex justify-between">
          {reflections?.content || reflections?.styleRules ? (
            <ConfirmClearDialog handleDeleteReflections={handleDelete} />
          ) : null}
          <Button
            onClick={() => setOpen(false)}
            className="bg-black hover:bg-gray-800 text-white px-4 py-2 rounded shadow transition"
          >
            <TighterText>Close</TighterText>
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
