import { ChatAnthropic } from "@langchain/anthropic";
import {
  type LangGraphRunnableConfig,
  type BaseStore,
  StateGraph,
  START,
} from "@langchain/langgraph";
import { ReflectionGraphAnnotation, ReflectionGraphReturnType } from "./state";
import { Memory } from "../../types";
import { REFLECT_SYSTEM_PROMPT } from "./prompts";
import { z } from "zod";

const ensureStoreFromConfig = (config: LangGraphRunnableConfig): BaseStore => {
  if (!config.store) {
    throw new Error("`store` not found in config");
  }

  return config.store;
};

const formatMemories = (memories: Memory): string => {
  const styleString = `The following is a list of style guidelines previously generated by you:
<style-guidelines>
- ${memories.styleRules.join("\n- ")}
</style-guidelines>`;
  const contentString = `The following is a list of memories/facts you previously generated about the user:
<user-facts>
- ${memories.content.join("\n- ")}
</user-facts>`;

  return styleString + "\n\n" + contentString;
};

export const reflect = async (
  state: typeof ReflectionGraphAnnotation.State,
  config: LangGraphRunnableConfig
): Promise<ReflectionGraphReturnType> => {
  const store = ensureStoreFromConfig(config);
  const assistantId = config.configurable?.assistant_id;
  if (!assistantId) {
    throw new Error("`assistant_id` not found in configurable");
  }
  const memoryNamespace = ["memories", assistantId];
  const memoryKey = "reflection";
  const memories = await store.get(memoryNamespace, memoryKey);

  const memoriesAsString = memories?.value
    ? formatMemories(memories.value as Memory)
    : "No memories found.";

  const generateReflectionsSchema = z.object({
    styleRules: z
      .array(z.string())
      .describe("The complete new list of style rules and guidelines."),
    content: z
      .array(z.string())
      .describe("The complete new list of memories/facts about the user."),
  });

  const model = new ChatAnthropic({
    model: "claude-3-5-sonnet-20240620",
    temperature: 0,
  }).withStructuredOutput(generateReflectionsSchema, {
    name: "generate_reflections",
  });

  const formattedSystemPrompt = REFLECT_SYSTEM_PROMPT.replace(
    "{artifact}",
    state.artifact?.content ?? "No artifact found."
  ).replace("{reflections}", memoriesAsString);

  const result = await model.invoke([
    {
      role: "system",
      content: formattedSystemPrompt,
    },
    ...state.messages,
  ]);

  const newMemories = {
    styleRules: result.styleRules,
    content: result.content,
  };

  await store.put(memoryNamespace, memoryKey, newMemories);

  return {};
};

const builder = new StateGraph(ReflectionGraphAnnotation)
  .addNode("reflect", reflect)
  .addEdge(START, "reflect");

export const graph = builder.compile();
