import { ANTHROPIC_MODELS, OPENAI_MODELS, FIREWORKS_MODELS, GEMINI_MODELS } from "@/constants";

export const ALL_MODELS = [
  ...ANTHROPIC_MODELS,
  ...OPENAI_MODELS,
  ...FIREWORKS_MODELS,
  ...GEMINI_MODELS,
];